"""empty message

Revision ID: 6c0275f458c0
Revises: ecae4263a0de
Create Date: 2021-12-11 15:59:43.866309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c0275f458c0'
down_revision = 'ecae4263a0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_uuid', sa.Integer(), nullable=False))
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_uuid'], ['uuid'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['department_id'], ['id'])
    op.drop_column('employee', 'department_uuid')
    # ### end Alembic commands ###
