"""empty message

Revision ID: 866ea5c8a119
Revises: 
Create Date: 2021-11-26 11:41:31.738006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866ea5c8a119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('position', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'position')
    # ### end Alembic commands ###
