"""empty message

Revision ID: ecae4263a0de
Revises: ed1273023eb5
Create Date: 2021-12-11 15:54:16.094548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecae4263a0de'
down_revision = 'ed1273023eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'department', ['uuid'])
    op.add_column('employee', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'employee', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'uuid')
    op.drop_constraint(None, 'department', type_='unique')
    # ### end Alembic commands ###
